defmodule CityImport do
  alias UsualWeather.{City, Repo}

  @cities [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Ottawa",
    "Calgary",
    "Edmonton",
    "Quebec City",
    "Winnipeg",
    "Hamilton",
    "Kitchener",
    "London",
    "St. Catharines",
    "Halifax",
    "Oshawa",
    "Victoria",
    "Windsor",
    "Saskatoon",
    "Regina",
    "Sherbrooke",
    "St. John’s",
    "Barrie",
    "Kelowna",
    "Abbotsford",
    "Sudbury",
    "Kingston",
    "Saguenay",
    "Trois-Rivières",
    "Guelph",
    "Moncton",
    "Brantford",
    "Thunder Bay",
    "Peterborough",
    "Lethbridge",
    "Chatham-Kent",
    "Cape Breton",
    "Kamloops",
    "Nanaimo",
    "Fredericton",
    "Belleville",
    "Chilliwack",
    "Red Deer",
    "Sarnia",
    "Drummondville",
    "Prince George",
    "Sault Ste. Marie",
    "Granby",
    "Kawartha Lakes",
    "Medicine Hat",
    "Charlottetown",
    "North Bay",
    "Norfolk",
    "Cornwall",
    "Vernon",
    "Saint-Hyacinthe",
    "Courtenay",
    "Grande Prairie",
    "Shawinigan",
    "Brandon",
    "Rimouski",
    "Leamington",
    "Sorel-Tracy",
    "Joliette",
    "Victoriaville",
    "Truro",
    "Duncan",
    "Timmins",
    "Prince Albert",
    "Penticton",
    "Rouyn-Noranda",
    "Orillia",
    "Salaberry-de-Valleyfield",
    "Brockville",
    "Woodstock",
    "Campbell River",
    "New Glasgow",
    "Midland",
    "Moose Jaw",
    "Bathurst",
    "Val-d’Or",
    "Alma",
    "Owen Sound",
    "Stratford",
    "Lloydminster",
    "Baie-Comeau",
    "Sept-Îles",
    "Miramichi",
    "Thetford Mines",
    "Parksville",
    "Rivière-du-Loup",
    "Corner Brook",
    "Centre Wellington",
    "Whitehorse",
    "Okotoks",
    "Edmundston",
    "Collingwood",
    "Yellowknife",
    "Cobourg",
    "Matane",
    "Squamish",
    "Camrose",
    "Amos"
  ]

  def import! do
    @cities
    |> Enum.each(&import_city/1)
  end

  defp import_city(name) do
    changeset = %City.changeset(%{City}, %{name: name})
    Repo.insert!(changeset)
  end
end

CityImport.import!
